# Generated by Django 4.0.1 on 2022-02-01 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='email',
            new_name='userEmail',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='password',
            new_name='userPass',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='name',
            new_name='username',
        ),
    ]
