# Generated by Django 4.0.1 on 2022-02-01 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_email_myuser_useremail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='age',
            new_name='studentage',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='email',
            new_name='studentemail',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='studentname',
        ),
    ]
