# Generated by Django 4.0.1 on 2022-02-02 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_track_name_student_trackname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='username',
            new_name='myusername',
        ),
    ]
