# Generated by Django 4.0.1 on 2022-02-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_myuser_myusername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='userEmail',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='userPass',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
