# Generated by Django 4.0.1 on 2022-02-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_myuser_useremail_alter_myuser_userpass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackname', models.CharField(max_length=20)),
            ],
        ),
    ]
